[config]
schemaVersion = "0.0.1"

[package]
namespace = "innominata"
name = "StarsandHitpoints"
versionNumber = "1.0.1"
description = "Adds a HP bar to scolomorphs"
websiteUrl = "https://github.com/innominata/StarsandHitpoints"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack_Starsand"= "5.4.16"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./"

[[build.copy]]
source = "./obj/Debug/net472/StarsandHitpoints.dll"
target = "./StarsandHitpoints.dll"

[publish]
repository = "https://starsand.thunderstore.io"
communities = ["starsand"]
categories = []